config/routes.rb
Rails.application.routes.draw do

  get 'warehouses/new'
  get 'warehouses/create'
  root to: 'products#index'
  get 'stocks/edit/:id' => 'stocks#edit', as: :edit_stocks
  post 'stocks/update' => 'stocks#update', as: :update_stocks
  get 'stocks/get_stock' => 'stocks#get_stock', as: :get_stock
  get 'warehouses/new' => 'warehouses#new', as: :new_warehouse
  post 'warehouses/create' => 'warehouses#create', as: :create_warehouse

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :stocks, dependent: :destroy

  def self.get_all_product_with_warehouse_and_count
    collection = Array.new
    Stock.filter_by_product.each_pair do |key, value|
      row  = Product.find(key).slice('id','sku_code', 'price')
      value_hash = value.collect{|i| [i.warehouse_id.to_s + '_warehouse', i.item_count]}.to_h
      value_hash1 = value.collect{|i| [i.warehouse_id.to_s + '_color_red', i.item_count < i.low_item_threshold]}.to_h
      row.merge!(value_hash)
      row.merge!(value_hash1)
      collection.push(row)
    end
    collection
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :warehouse
  belongs_to :product
  attr_accessor :name
  validates_presence_of :low_item_threshold, :item_count

  scope :filter_by_product, -> {all.group_by(&:product_id)}
  scope :find_by_product_and_warehouse, -> (product_id, warehouse_id) {find_by(product_id: product_id, warehouse_id: warehouse_id)}
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :stocks, dependent: :destroy
  validates :name, :wh_code,:max_capacity, :pincode,  presence: true
  validates :name, :wh_code, uniqueness: { case_sensitive: false }
  validates_length_of :wh_code, :within => 4..12
  validates_length_of :pincode, :is => 6

  scope :find_warehouse_id, -> (name)  {find_by(name: name).id}

  def create_stock
    Product.pluck(:id).each do |product_id|
      self.stocks.create(product_id: product_id, item_count: ITEM_COUNT, low_item_threshold: THRESHOLD_COUNT)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  def index
    @product = Product.get_all_product_with_warehouse_and_count
    @header = ['id', 'sku_code', 'price'] + Warehouse.pluck(:id).map{|i| i.to_s + '_warehouse'} + Warehouse.pluck(:id).map{|i| i.to_s + '_color_red'}
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def edit
    product_id = params[:id]
    warehouse_id = Warehouse.find_warehouse_id(DEFAULT_WAREHOUSE)
    @stock = Stock.find_by_product_and_warehouse(product_id, warehouse_id)
  end

  def update
    stock = get_stock_details(params[:stock][:product_id], params[:stock][:warehouse_id])
    stock.update(stock_params)
    redirect_to root_path, notice: 'Product updated successfully'
  end

  def get_stock
    stock = get_stock_details(params[:product_id], params[:warehouse_id])
    render json: stock
  end

  private

  def stock_params
    params.require(:stock).permit(:item_count, :low_item_threshold)
  end

  def get_stock_details(product_id, warehouse_id)
    Stock.find_by_product_and_warehouse(product_id, warehouse_id)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :check_product, only: :new
  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.create(warehouse_params)
    if @warehouse.persisted?
      @warehouse.create_stock
      redirect_to root_path, :notice => "Warehouse Created Successfully"
    else
      render :new
    end
  end

  private
  def warehouse_params
    params.require(:warehouse).permit(:name, :wh_code, :max_capacity, :pincode)
  end

  def check_product
    redirect_to root_path, :alert => "Sorry there are no product, Please create Product first" unless Product.any?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def skip_record_if_is_color_header(header)
    header.include?('_color_red') || header.include?('id')
  end

  def check_product_below_threshold(header, product)
    header.include?('_warehouse') && product[header.gsub('_warehouse','_color_red')]
  end

  def get_warehouse_name(header)
    Warehouse.find_by(id: header.sub('_warehouse','')).name
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryManagementSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
<p class = "notice"> <%= flash[:notice] %> </p>
<% elsif flash[:alert] %>
<p class = "alert"> <% flash[:alert]  %> </p>
<% end%>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1> All Products </h1>
<% if @product.any? %>
  <%= link_to 'New Warehouse', new_warehouse_path %>
<% end %>
<table id="product-table">
  <thead>
  <tr>
    <% @header.each do |header| %>
        <% next if skip_record_if_is_color_header(header) %>
        <th>
          <%= header.include?('_warehouse') ? get_warehouse_name(header) : header %>
        </th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% if @product.any? %>
    <% @product.each do |product| %>
        <tr>
          <% @header.each do |header| %>
              <% next if skip_record_if_is_color_header(header) %>
              <% if header.include?('sku_code') %>
                  <td>
                    <%= link_to product[header], edit_stocks_path(product["id"]) %>
                  </td>
              <% else %>
                  <td class="<%= ("red" if check_product_below_threshold(header, product)) %>">
                    <%= product[header] %>
                  </td>
              <% end %>

          <% end %>
        </tr>
    <% end %>
  <% else %>
  <tr>
    <td> No products Available </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/stocks/edit.html.erb
<h1> Stocks Edit </h1>

<%= form_for(@stock, :url => update_stocks_path, :method => 'post', id: 'stock_update_form') do |f|%>
    <table>
      <tr>
        <th> Name </th>
        <td><%= f.text_field :name, value: @stock.product.name,readonly: true %></td>
        <td><%= f.hidden_field :product_id%></td>
      </tr>
      <tr>
        <th> Warehouse </th>
        <td><%= f.select :warehouse_id, options_for_select(Warehouse.all.map{ |s| [s[:name], s[:id]]}, @stock.warehouse_id)%></td>
      </tr>
      <tr>
        <th> Item Count </th>
        <td><%=f.text_field :item_count, required: true %></td>
      </tr>
      <tr>
        <th> Low Item Threshold </th>
        <td><%=f.text_field :low_item_threshold, required: true %></td>
      </tr>
      <tr>
        <td>
          <%= f.submit('Update Stock')%>
        </td>
      </tr>

    </table>

<% end%>

app/views/warehouses/new.html.erb
<h1> Warehouse Create </h1>

<%= form_for(@warehouse, :url => create_warehouse_path, :method => 'post', id: 'warehouse_create_form') do |f|%>

    <% if @warehouse.errors.any? %>
        <h1> Errors </h1>
        <ul>
          <% @warehouse.errors.full_messages.each do |message|%>
            <li> <%= message %> </li>
          <% end %>
        </ul>
    <% end %>
    <table>
      <tr>
        <th> Name </th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th> Wh Code </th>
        <td><%= f.text_field :wh_code %></td>
      </tr>
      <tr>
        <th> Pincode </th>
        <td><%= f.text_field :pincode %></td>
      </tr>
      <tr>
        <th> Max Capacity </th>
        <td><%=f.text_field :max_capacity %></td>
      </tr>
      <tr>
        <td>
          <%= f.submit('Update Stock')%>
        </td>
      </tr>
    </table>
<% end%>